(defmacro mk-slotpair (regular-slot sub-slot)
  `(cons ,regular-slot ,sub-slot))
(defmacro slotpair-regular (slotpair)
  `(car ,slotpair))
(defmacro slotpair-sub (slotpair)
  `(cdr ,slotpair))

(defmacro mk-depnode* (stype content &optional (match nil))
  `(cons (cons ,stype ,content) ,match))
(defmacro depnode*-type (n)
  `(caar ,n))
(defmacro depnode*-content (n)
  `(cdar ,n))
(defmacro depnode*-match (n)
  `(cdr ,n))

(defmacro mk-revmatch (category pkgname version pathlist)
  `(list ,category ,pkgname ,version ,pathlist))
(defmacro revmatch-category (r)
  `(car ,r))
(defmacro revmatch-pkgname (r)
  `(cadr ,r))
(defmacro revmatch-version (r)
  `(caddr ,r))
(defmacro revmatch-pathlist (r)
  `(cadddr ,r))

(defmacro pkgrec-category (pkgrec)
  `(car ,pkgrec))
(defmacro pkgrec-pkgname (pkgrec)
  `(cadr ,pkgrec))
(defmacro pkgrec-version (pkgrec)
  `(caddr ,pkgrec))
(defmacro pkgrec-locaux (pkgrec)
  `(cadddr ,pkgrec))
(defmacro pkgrec-grplst (pkgrec)
  `(nth 4 ,pkgrec))
(defmacro pkgrec-uselst (pkgrec)
  `(nth 5 ,pkgrec))
(defmacro pkgrec-iuse_effective (pkgrec)
  `(nth 6 ,pkgrec))
(defmacro pkgrec-slotpair (pkgrec)
  `(nth 7 ,pkgrec))
(defmacro pkgrec-depnode*-bdep (pkgrec)
  `(nth 8 ,pkgrec))
(defmacro pkgrec-depnode*-idep (pkgrec)
  `(nth 9 ,pkgrec))
(defmacro pkgrec-depnode*-rdep (pkgrec)
  `(nth 10 ,pkgrec))
(defmacro pkgrec-depnode*-pdep (pkgrec)
  `(nth 11 ,pkgrec))
(defmacro pkgrec-depnode* (pkgrec class-idx)
  `(nth (+ 8 ,class-idx) ,pkgrec))
(defmacro pkgrec-reverse-bdep (pkgrec)
  `(nth 12 ,pkgrec))
(defmacro pkgrec-reverse-idep (pkgrec)
  `(nth 13 ,pkgrec))
(defmacro pkgrec-reverse-rdep (pkgrec)
  `(nth 14 ,pkgrec))
(defmacro pkgrec-reverse-pdep (pkgrec)
  `(nth 15 ,pkgrec))
(defmacro pkgrec-reverse (pkgrec class-idx)
  `(nth (+ 12 ,class-idx) ,pkgrec))
(defmacro pkgrec-status (pkgrec)
  `(nth 16 ,pkgrec))
(defmacro mk-pkgrec (category pkgname version locaux grplst uselst iuse-effective slotpair &optional bdep idep rdep pdep rev-bdep rev-idep rev-rdep rev-pdep (status :not-built))
  `(list ,category ,pkgname ,version ,locaux ,grplst ,uselst ,iuse-effective ,slotpair ,bdep ,idep ,rdep ,pdep ,rev-bdep ,rev-idep ,rev-rdep ,rev-pdep ,status))
