.TH repo.conf 5 2023-09-10 1.0.0 易构建软件包管理器
.SH 名称
repo.conf \- ebuild 仓库的配置文件

.SH 描述
.PP
repo.conf 是每个 ebuild 仓库的配置文件。文件中从 \fB#\fP 字符到行尾的内容是注释，空白行忽略。
.br
文件的内容由若干个段组成，每个段的第一行是段标识符，格式为一个用方括号括起来的段名称，剩下的是段的内容，各个段内容的格式和含义见下面的描述。
.br
段和段之间没有分隔符，每个段从段标识符开始，到下一个段标识符的前一行或文件尾结束。
.PP
repo.conf 中有以下几个段：
.TP
\fB[属性]\fP\ 
用于记录仓库的各项属性。每一行的格式为：\fB\fI属性\fP=\fI值\fP\fR，以下是各个属性以及它们的含义：
.sp
\(bu\h'+03'\c
\fBremote\fP。远程仓库用来同步的 \fIurl\fP，如果是本地仓库该属性的值为 \fBfalse\fP。
.sp
\(bu\h'+03'\c
\fBfull\-sync\fP。远程仓库是否完全同步，取值为 \fBtrue\fP 或 \fBfalse\fP，本地仓库该属性忽略。
.sp
\(bu\h'+03'\c
\fBenable\fP。仓库的优先级，值为一个非负整数，数字越大优先级越高，\fB0\fP 表示禁用仓库。
.sp
\(bu\h'+03'\c
\fBprofile\fP。仓库中当前使用的系统轮廓。
.TP
\fB[文件清单]\fP
除了 repo.conf 外仓库中所有的文件、目录和符号链接，以及它们的相关信息。
.br
每一行有 4 个字段，第一个字段是文件类型，用一个字符来表示：“\fBd\fP”代表目录，“\fB-\fP”代表普通文件，“\fBl\fP”代表符号链接。
.br
第二个字段是带路径的文件名，其中的路径是相对于仓库根目录的路径。
.br
对于普通文件而言，第三个字段是文件大小，以字节为单位，第四个字段是文件的 sha256 校验和。
.br
对于符号链接而言，第三个字段是字符串“\fB->\fP”，第四个字段是链接目标。
.br
对于目录而言，第三个和第四个字段都是以一个连字符表示的占位符。
.br
字段之间以一个或多个空格或水平制表符分隔。
.PP
repo.conf 不会在主仓库和从属仓库之间叠加。
.PP
当创建本地仓库时，\fBebuild\fP 会扫描仓库中的文件（如果是非独立仓库则不包括主仓库中的文件）生成文件清单，并根据命令选项设定各个属性的值。
.br
当添加远程仓库时，\fBebuild\fP 首先会下载文件清单，根据命令选项设定各个属性的值，随后会视情况同步仓库中的文件。
.br
当更新 repo.conf 中的文件清单时情况与创建或添加类似，如果是本地仓库，\fBebuild\fP 会扫描仓库中的文件来更新文件清单，如果是远程仓库，\fBebuild\fP 会下载文件清单来执行更新。

.SH 亦见
.BR ebuild (1),
.BR ebuild.conf (5)
